# SPDX-FileCopyrightText: 2026 ash contributors <https://github.com/ash-project/ash/graphs/contributors>
# SPDX-License-Identifier: MIT

defmodule Ash.Conformance.Report.Ecosystem do
  @moduledoc """
  Every registered data layer, surveyed and reported side by side.

  Each adapter is surveyed: its results are classified against the intended
  answers, whether or not it has reviewed expectations, so every column means
  the same thing. An adapter whose storage cannot be set up, for example
  because its database is not running, is listed as not run with the reason.
  """
  alias Ash.Conformance.{Adapter, Resources, Survey}
  alias Ash.Conformance.Report.FeatureReport

  @classifications ~w(works rejected wrong crashed setup_failed open_question)a

  def run(adapters \\ Adapter.every()) do
    Enum.map(adapters, fn adapter ->
      try do
        rows = Survey.run(adapter)
        %{adapter: adapter, rows: rows, warnings: Resources.warnings(adapter), unavailable: nil}
      rescue
        exception ->
          reason = exception |> Exception.message() |> String.split("\n") |> hd()
          %{adapter: adapter, rows: [], warnings: [], unavailable: reason}
      end
    end)
  end

  def markdown(results) do
    adapters = Enum.map(results, & &1.adapter)
    rows = Enum.flat_map(results, & &1.rows)

    unavailable =
      for %{unavailable: reason, adapter: adapter} <- results,
          reason,
          into: %{},
          do: {adapter.id(), reason}

    {sections, summaries} =
      FeatureReport.feature_tables(rows, adapters, detail: :none, unavailable: unavailable)

    """
    <!-- SPDX-FileCopyrightText: 2026 ash contributors <https://github.com/ash-project/ash/graphs/contributors> -->
    <!-- SPDX-License-Identifier: MIT -->
    # Ash data layers compared

    Generated by `mix conformance.ecosystem`. Every data layer below was
    surveyed: each scenario's result was classified automatically against the
    answer Ash defines. Reviewed adapters also have strict, recorded contracts
    in [FEATURES.md](FEATURES.md); the others have not been reviewed, so read
    their results as observations. Each data layer's failing scenarios are listed in
    `surveys/features-<adapter>.md`.

    ## Data layers

    | Column | Data layer | Version | Reviewed | #{Enum.map_join(@classifications, " | ", &heading/1)} | Definition warnings |
    | --- | --- | --- | --- | #{Enum.map_join(@classifications, " | ", fn _ -> "---:" end)} | ---: |
    #{Enum.map_join(results, "\n", &summary_row/1)}

    #{FeatureReport.legend()}
    | ➖ Not run | The data layer's storage could not be set up for this run. |

    #{sections}
    #{FeatureReport.claims_section(adapters, summaries)}
    ## Setup failures

    A setup failure means the data layer could not store or read back a
    scenario's fixture, so the scenario never ran its operation. These are the
    distinct reasons, with how many scenarios each stopped.

    #{Enum.map_join(results, "\n", &setup_failures_section/1)}
    ## Definition warnings

    Ash checks each shared resource against its data layer when the resource is
    defined. These are the distinct reasons it gave, with how many resources
    each affected. A warning means a resource used something the data layer
    does not advertise; the scenarios above show what happened anyway.

    #{Enum.map_join(results, "\n", &warnings_section/1)}
    """
  end

  def write!(results, dir \\ ".") do
    File.write!(Path.join(dir, "ECOSYSTEM.md"), markdown(results))

    for %{rows: rows, adapter: adapter, unavailable: nil} <- results do
      Survey.write!(adapter, rows, Path.join(dir, "surveys"))
    end

    :ok
  end

  defp heading(classification),
    do: classification |> to_string() |> String.replace("_", " ") |> String.capitalize()

  defp summary_row(%{adapter: adapter, unavailable: reason}) when is_binary(reason) do
    blanks = Enum.map_join(@classifications, " | ", fn _ -> "" end)

    "| #{adapter.id()} | #{adapter.label()} | #{version(adapter)} | #{reviewed(adapter)} | #{blanks} | Not run: #{reason} |"
  end

  defp summary_row(%{adapter: adapter, rows: rows, warnings: warnings}) do
    counts = Enum.frequencies_by(rows, & &1.classification)
    cells = Enum.map_join(@classifications, " | ", &Map.get(counts, &1, 0))
    warning_count = warnings |> Enum.map(&elem(&1, 1)) |> Enum.sum()

    "| #{adapter.id()} | #{adapter.label()} | #{version(adapter)} | #{reviewed(adapter)} | #{cells} | #{warning_count} |"
  end

  defp reviewed(adapter), do: if(Adapter.reviewed?(adapter), do: "yes", else: "no")

  # Git-pinned data layers also show the commit, since their version number
  # does not identify unreleased work.
  defp version(adapter) do
    vsn =
      case Application.spec(adapter.package(), :vsn) do
        nil -> "unknown"
        vsn -> to_string(vsn)
      end

    case Map.get(Mix.Dep.Lock.read(), adapter.package()) do
      {:git, _url, ref, _opts} -> "#{vsn} (`#{String.slice(ref, 0, 7)}`)"
      _ -> vsn
    end
  end

  defp setup_failures_section(%{adapter: adapter, unavailable: reason}) when is_binary(reason),
    do: "### #{adapter.label()}\n\nNot run: #{reason}\n"

  defp setup_failures_section(%{adapter: adapter, rows: rows}) do
    reasons =
      for %{classification: :setup_failed, actual: actual} <- rows do
        actual
        |> String.split("Setup failed:", parts: 2)
        |> List.last()
        |> String.split("\n")
        |> Enum.map(&(&1 |> String.trim() |> String.trim_leading("* ")))
        |> Enum.find("", &(&1 not in ["", "Unknown Error"]))
        |> String.split(". ", parts: 2)
        |> hd()
        |> String.slice(0, 200)
        |> String.replace("|", "\\|")
      end

    case reasons |> Enum.frequencies() |> Enum.sort_by(fn {r, n} -> {-n, r} end) do
      [] ->
        "### #{adapter.label()}\n\nNone.\n"

      counts ->
        rows = Enum.map_join(counts, "\n", fn {reason, count} -> "| #{count} | #{reason} |" end)
        "### #{adapter.label()}\n\n| Scenarios | Reason |\n| ---: | --- |\n#{rows}\n"
    end
  end

  defp warnings_section(%{adapter: adapter, warnings: []}),
    do: "### #{adapter.label()}\n\nNone.\n"

  defp warnings_section(%{adapter: adapter, warnings: warnings}) do
    rows = Enum.map_join(warnings, "\n", fn {message, count} -> "| #{count} | #{message} |" end)
    "### #{adapter.label()}\n\n| Resources | Warning |\n| ---: | --- |\n#{rows}\n"
  end
end
