# SPDX-FileCopyrightText: 2026 ash contributors <https://github.com/ash-project/ash/graphs/contributors>
# SPDX-License-Identifier: MIT

defmodule Ash.Conformance.Report.Ecosystem do
  @moduledoc """
  Every registered data layer, surveyed and reported side by side.

  Each adapter is surveyed: its results are classified against the intended
  answers, whether or not it has reviewed expectations, so every column means
  the same thing. An adapter whose storage cannot be set up, for example
  because its database is not running, is listed as not run with the reason.
  """
  alias Ash.Conformance.{Adapter, Blockers, Resources, Survey}
  alias Ash.Conformance.Report.FeatureReport

  @classifications ~w(works rejected wrong order_dependent crashed setup_failed open_question)a

  def run(adapters \\ Adapter.every()) do
    Enum.map(adapters, fn adapter ->
      try do
        rows = Survey.run(adapter)
        %{adapter: adapter, rows: rows, warnings: Resources.warnings(adapter), unavailable: nil}
      rescue
        exception ->
          reason = exception |> Exception.message() |> String.split("\n") |> hd()
          %{adapter: adapter, rows: [], warnings: [], unavailable: reason}
      end
    end)
  end

  def markdown(results) do
    adapters = Enum.map(results, & &1.adapter)
    rows = Enum.flat_map(results, & &1.rows)

    unavailable =
      for %{unavailable: reason, adapter: adapter} <- results,
          reason,
          into: %{},
          do: {adapter.id(), reason}

    {sections, summaries} =
      FeatureReport.feature_tables(rows, adapters, detail: :none, unavailable: unavailable)

    """
    <!-- SPDX-FileCopyrightText: 2026 ash contributors <https://github.com/ash-project/ash/graphs/contributors> -->
    <!-- SPDX-License-Identifier: MIT -->
    # Ash data layers compared

    Generated by `mix conformance.ecosystem`. Every data layer below was
    surveyed: each scenario's result was classified automatically against the
    answer Ash defines. Reviewed adapters also have strict, recorded contracts
    in [FEATURES.md](FEATURES.md); the others have not been reviewed, so read
    their results as observations. Each data layer's failing scenarios are listed in
    `surveys/features-<adapter>.md`.

    ## Data layers

    | Column | Data layer | Version | Reviewed | #{Enum.map_join(@classifications, " | ", &heading/1)} | Blocked | Definition warnings |
    | --- | --- | --- | --- | #{Enum.map_join(@classifications, " | ", fn _ -> "---:" end)} | ---: | ---: |
    #{Enum.map_join(results, "\n", &summary_row/1)}

    Blocked counts results in the columns before it that have a failing
    prerequisite, such as a type the data layer cannot store; see
    [Blockers](#blockers).

    #{notes_section(adapters)}
    #{Ash.Conformance.Report.StorageGrid.markdown(results)}
    #{Ash.Conformance.Report.OperationGrid.markdown(results)}
    #{Ash.Conformance.Report.PolicyGrid.markdown(results)}
    #{FeatureReport.legend()}
    | ➖ Not run | The data layer's storage could not be set up for this run. |

    #{sections}
    ## Blockers

    A blocker is a failing prerequisite that may explain other results, so
    fix it first. Prerequisites are either declared by a scenario (a control
    that runs the same path without the feature under test, or the storage
    cell of a type it relies on), or, when a fixture row could not be stored,
    the storage cells of that row's types. A setup failure never ran its
    operation, so its result is unknown, not broken. A scenario with several
    blockers counts under each.

    #{Enum.map_join(results, "\n", &blockers_section/1)}
    #{FeatureReport.claims_section(adapters, summaries)}
    ## Definition warnings

    Ash checks each shared resource against its data layer when the resource is
    defined. These are the distinct reasons it gave, with how many resources
    each affected. A warning means a resource used something the data layer
    does not advertise; the scenarios above show what happened anyway.

    #{Enum.map_join(results, "\n", &warnings_section/1)}
    """
  end

  def write!(results, dir \\ ".") do
    File.write!(Path.join(dir, "ECOSYSTEM.md"), markdown(results))

    for %{rows: rows, adapter: adapter, unavailable: nil} <- results do
      Survey.write!(adapter, rows, Path.join(dir, "surveys"))
    end

    :ok
  end

  defp notes_section(adapters) do
    notes =
      for adapter <- adapters, note <- adapter.notes(), do: "- **#{adapter.label()}:** #{note}"

    if notes == [] do
      ""
    else
      """
      ### Setup notes

      Where the suite had to do something other than configure the data layer
      as an application would, and why:

      #{Enum.join(notes, "\n")}
      """
    end
  end

  defp heading(classification),
    do: classification |> to_string() |> String.replace("_", " ") |> String.capitalize()

  defp summary_row(%{adapter: adapter, unavailable: reason}) when is_binary(reason) do
    blanks = Enum.map_join(@classifications, " | ", fn _ -> "" end)

    "| #{adapter.id()} | #{adapter.label()} | #{version(adapter)} | #{reviewed(adapter)} | #{blanks} | | Not run: #{reason} |"
  end

  defp summary_row(%{adapter: adapter, rows: rows, warnings: warnings}) do
    counts = Enum.frequencies_by(rows, & &1.classification)
    cells = Enum.map_join(@classifications, " | ", &Map.get(counts, &1, 0))
    warning_count = warnings |> Enum.map(&elem(&1, 1)) |> Enum.sum()
    blocked = Enum.count(rows, &(Map.get(&1, :blocked_by, []) != []))

    "| #{adapter.id()} | #{adapter.label()} | #{version(adapter)} | #{reviewed(adapter)} | #{cells} | #{blocked} | #{warning_count} |"
  end

  defp reviewed(adapter), do: if(Adapter.reviewed?(adapter), do: "yes", else: "no")

  # Git-pinned data layers also show the commit, since their version number
  # does not identify unreleased work.
  defp version(adapter) do
    vsn =
      case Application.spec(adapter.package(), :vsn) do
        nil -> "unknown"
        vsn -> to_string(vsn)
      end

    case Map.get(Mix.Dep.Lock.read(), adapter.package()) do
      {:git, _url, ref, _opts} -> "#{vsn} (`#{String.slice(ref, 0, 7)}`)"
      _ -> vsn
    end
  end

  defp blockers_section(%{adapter: adapter, unavailable: reason}) when is_binary(reason),
    do: "### #{adapter.label()}\n\nNot run: #{reason}\n"

  defp blockers_section(%{adapter: adapter, rows: rows}),
    do: "### #{adapter.label()}\n\n#{Blockers.markdown(rows)}"

  defp warnings_section(%{adapter: adapter, warnings: []}),
    do: "### #{adapter.label()}\n\nNone.\n"

  defp warnings_section(%{adapter: adapter, warnings: warnings}) do
    rows = Enum.map_join(warnings, "\n", fn {message, count} -> "| #{count} | #{message} |" end)
    "### #{adapter.label()}\n\n| Resources | Warning |\n| ---: | --- |\n#{rows}\n"
  end
end
