# SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule Ash.Conformance.Contracts.Gaps do
  @moduledoc """
  Every known gap, gathered from where its knowledge lives, and `GAPS.md`.

  - `Ash.Conformance.Contracts.SharedGaps`: Ash's own defects and undecided
    semantics, which apply to every data layer.
  - `Ash.Conformance.SQL.Gaps`: defects AshSQL causes on every data layer
    built on it.
  - Each adapter's `gaps/0`: what only that data layer shows, next to its
    expectation records.

  A gap has an ID (its `GAPS.md` anchor), a title, a kind and its owners.
  The first owner is where the fix starts; later owners also need changes,
  such as an adapter capability gate or context passed in by Ash.
  Implementations are defects to fix. Decisions are semantic questions for
  Ash to settle before any adapter can implement them. Limitations are
  unsupported by design; the documented rejection is the intended result.
  """

  alias Ash.Conformance.Adapter

  @names %{ash: "Ash", ash_sql: "AshSQL", ash_postgres: "AshPostgres", ash_sqlite: "AshSQLite"}

  @doc "Every gap: shared ones first, then AshSQL's, then each adapter's."
  def all do
    groups()
    |> Enum.flat_map(fn {_heading, gaps} -> gaps end)
    |> tap(&validate!/1)
  end

  defp groups do
    [
      {"Ash", Ash.Conformance.Contracts.SharedGaps.all()},
      {"AshSQL", Ash.Conformance.SQL.Gaps.all()}
    ] ++
      for adapter <- Adapter.every(), adapter.gaps() != [], do: {adapter.label(), adapter.gaps()}
  end

  def ids, do: Enum.map(all(), & &1.id)
  def fetch!(id), do: Enum.find(all(), &(&1.id == id)) || raise(KeyError, key: id, term: "gaps")
  def kind(id), do: fetch!(id).kind
  def owners(id), do: fetch!(id).owners
  def names(id), do: Enum.map(owners(id), &name/1)

  def id("GAPS.md#" <> id), do: id

  # Packages outside the shipped stack are named by their adapter's label.
  defp name(package) do
    Map.get(@names, package) ||
      Enum.find_value(Adapter.every(), &(&1.package() == package && &1.label())) ||
      to_string(package)
  end

  @doc "The owner line that opens a gap's `GAPS.md` section."
  def owner_line(id) do
    label =
      case kind(id) do
        :decision -> "Decision owner"
        :limitation -> "Limitation owner"
        :implementation -> "Owner"
      end

    "#{label}: #{Enum.join(names(id), ", then ")}."
  end

  defp validate!(gaps) do
    ids = Enum.map(gaps, & &1.id)

    if ids != Enum.uniq(ids),
      do: raise(ArgumentError, "Duplicate gap IDs: #{inspect(ids -- Enum.uniq(ids))}")

    for gap <- gaps do
      unless anchor(gap.title) == gap.id,
        do: raise(ArgumentError, "Gap #{gap.id}'s title #{inspect(gap.title)} must match its ID")

      unless gap.owners != [] and Enum.uniq(gap.owners) == gap.owners,
        do: raise(ArgumentError, "Gap #{gap.id} needs distinct owners")

      required = %{decision: "Decision:", limitation: "Limitation:"}[gap.kind]

      if required && !String.contains?(gap.body, required),
        do: raise(ArgumentError, "Gap #{gap.id} must state its #{required}")
    end

    :ok
  end

  defp anchor(title), do: title |> String.downcase() |> String.replace(" ", "-")

  @doc "`GAPS.md`: every gap, grouped by where it lives."
  def markdown do
    sections =
      Enum.map_join(groups(), "\n", fn {heading, gaps} ->
        entries =
          Enum.map_join(gaps, "\n", fn gap ->
            "## #{gap.title}\n\n#{owner_line(gap.id)}\n#{String.trim_trailing(gap.body)}\n"
          end)

        "# #{heading}\n\n#{entries}"
      end)

    """
    <!-- SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors> -->
    <!-- SPDX-License-Identifier: MIT -->

    # Known gaps

    Generated by `mix conformance.gaps`. Each entry is a local follow-up task;
    no GitHub issue is implied. Expectation records link each nonconforming
    result to an entry below. Unless marked as a decision, the shared scenario
    contains the intended result, and an observed result never replaces it
    automatically.

    Each entry names the project that owns the fix, in the order the work is
    needed. Decisions are semantic questions for Ash to settle before a data
    layer implements them. Entries are grouped by where their knowledge lives:
    Ash's shared defects and decisions (`lib/contracts/shared_gaps.ex`),
    AshSQL's defects (`lib/sql/gaps.ex`), then each data layer's own (its
    adapter's `gaps/0`).

    #{sections}
    """
  end
end
