# SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule Ash.Conformance.Report do
  @moduledoc false
  alias Ash.Conformance.{
    Adapter,
    Catalog,
    Contracts.Capabilities,
    Contracts.Expectations,
    Contracts.Gaps
  }

  def declaration_rows do
    for adapter <- Adapter.all(), scenario <- Catalog.for_adapter(adapter) do
      expectation = Expectations.for(scenario.id, adapter.id())

      %{
        scenario: scenario.id,
        description: scenario.description,
        profile: scenario.profile,
        fixture: Ash.Conformance.Scenario.fixture_name(scenario.fixture),
        semantic_basis: scenario.semantic_basis,
        benchmark: scenario.benchmark,
        capabilities: Capabilities.for_scenario(adapter, scenario),
        fallback: if(scenario.fallback, do: %{probe: scenario.fallback}, else: :unobserved),
        area: scenario.area,
        adapter: adapter.id(),
        status: status(expectation),
        task: task(expectation),
        owners: owners(expectation),
        expected: expected(scenario),
        accepted: accepted(scenario, expectation)
      }
    end
  end

  def status(:supported), do: :supported
  def status({status, _, _}), do: status
  def task(:supported), do: nil
  def task({_, _, task}), do: task
  def owners(:supported), do: []
  def owners({_, _, task}), do: task |> Gaps.id() |> Gaps.names()

  def outcome({:ok, actual}), do: value(actual)

  def outcome({:order_dependent, outcomes}) do
    seeds =
      Enum.map_join(Ash.Conformance.Runner.orders(), ". ", fn order ->
        "#{order} seed: #{outcome(Map.fetch!(outcomes, order))}"
      end)

    "Order-dependent. #{seeds}"
  end

  def outcome({:error, exception, message}) do
    # Stack frames contain source line numbers and function hashes, not result semantics.
    reason = message |> String.split(~r/\n\s+\([^)]+\) [^\n]*:\d+: /, parts: 2) |> hd()
    "#{inspect(exception)}: #{String.trim(reason)}"
  end

  def observation({:ok, _} = result), do: %{actual: outcome(result), details: nil}

  def observation({:order_dependent, outcomes} = result),
    do: %{
      actual: outcome(result),
      details: Map.new(outcomes, fn {order, outcome} -> {order, observation(outcome)} end)
    }

  def observation({:error, exception, message} = result),
    do: %{actual: outcome(result), details: "#{inspect(exception)}: #{message}"}

  defp expected(%{expected: :unresolved}), do: "Semantics unresolved"
  defp expected(scenario), do: value(scenario.expected)
  defp accepted(scenario, :supported), do: expected(scenario)
  defp accepted(_, {_, {:value, actual}, _}), do: value(actual)

  defp accepted(_, {:unknown, {:setup_error, pattern}, _}),
    do: "Not run: setup fails with #{inspect(pattern)}"

  defp accepted(scenario, {status, {:order_dependent, signatures}, task}) do
    seeds =
      Enum.map_join(Ash.Conformance.Runner.orders(), ". ", fn order ->
        "#{order} seed: #{accepted(scenario, {status, Map.fetch!(signatures, order), task})}"
      end)

    "Order-dependent. #{seeds}"
  end

  defp accepted(_, {_, {:error, exception, pattern}, _}),
    do: "#{inspect(exception)} matching #{inspect(pattern)}"

  # Maps print with sorted keys: small maps otherwise print in atom-creation
  # order, which changes between builds and would look like a changed result.
  def value(value),
    do:
      inspect(value,
        charlists: :as_lists,
        limit: :infinity,
        printable_limit: :infinity,
        custom_options: [sort_maps: true]
      )

  def matrix do
    rows = Enum.group_by(declaration_rows(), & &1.scenario)
    adapters = Enum.map(Adapter.all(), & &1.id())

    header = """
    <!-- SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors> -->
    <!-- SPDX-License-Identifier: MIT -->

    # Data-layer expectation matrix

    Generated by `mix conformance.matrix`. These are declared contracts; `results/` contains execution results. Passing an unsupported, known-defect or unresolved expectation does not establish feature conformance.

    Elixir scenarios and expectations define the contract. CI runs each adapter independently and uploads its observations. Compare saved result files with `mix conformance.compare`.

    | Scenario | #{Enum.join(adapters, " | ")} |
    | --- | #{Enum.map_join(adapters, " | ", fn _ -> "---" end)} |
    """

    body =
      Enum.map_join(Catalog.all(), "\n", fn scenario ->
        cells =
          Enum.map(adapters, fn adapter ->
            row = Enum.find(Map.fetch!(rows, scenario.id), &(&1.adapter == adapter))

            case row do
              nil -> "profile unavailable"
              %{task: nil} -> to_string(row.status)
              _ -> "[#{row.status}](#{row.task}) · #{hd(row.owners)}"
            end
          end)

        source = "#{scenario.source.file}#L#{scenario.source.line}"
        "| [`#{scenario.id}`](#{source}) | #{Enum.join(cells, " | ")} |"
      end)

    header <> body <> "\n" <> owner_table(rows |> Map.values() |> List.flatten())
  end

  defp owner_table(rows) do
    adapters = Enum.map(Adapter.all(), & &1.id())

    counts =
      rows
      |> Enum.filter(& &1.task)
      |> Enum.frequencies_by(&{Gaps.id(&1.task), &1.adapter})

    body =
      Gaps.ids()
      |> Enum.sort_by(&{Gaps.names(&1), &1})
      |> Enum.map_join("\n", fn id ->
        "| [#{id}](GAPS.md##{id}) | #{Enum.join(Gaps.names(id), ", then ")} | #{Gaps.kind(id)} | " <>
          Enum.map_join(adapters, " | ", &Map.get(counts, {id, &1}, 0)) <> " |"
      end)

    """

    ## Gaps by owner

    The first owner is where the fix starts. Counts are scenarios linked to each gap.

    | Gap | Owner | Kind | #{Enum.join(adapters, " | ")} |
    | --- | --- | --- | #{Enum.map_join(adapters, " | ", fn _ -> "---:" end)} |
    #{body}
    """
  end

  def console(rows) do
    rows
    |> Enum.sort_by(&{&1.scenario, &1.adapter})
    |> Enum.map_join("\n", fn row ->
      "[#{verdict(row)}] #{row.adapter} #{row.scenario} (#{row.status})\n" <>
        "  intended: #{compact(row.expected)}\n" <>
        "  observed: #{compact(row.actual)}" <>
        if(row.status == :supported, do: "", else: "\n  accepted: #{compact(row.accepted)}")
    end)
  end

  def summary(rows, comparison) do
    counts = Enum.frequencies_by(rows, &{&1.adapter, &1.status, &1.execution})

    count_rows =
      counts
      |> Enum.sort()
      |> Enum.map_join("\n", fn {{adapter, status, execution}, count} ->
        "| #{adapter} | #{status} | #{execution} | #{count} |"
      end)

    sections = [
      {"Failed checks", Enum.filter(rows, &(&1.execution == :failed)), " open"},
      {"Supported checks", Enum.filter(rows, &(&1.status == :supported)), ""},
      {"Unsupported checks", Enum.filter(rows, &(&1.status == :unsupported)), ""},
      {"Known defects", Enum.filter(rows, &(&1.status == :known_defect)), ""},
      {"Unresolved semantics", Enum.filter(rows, &(&1.status == :unresolved)), ""}
    ]

    details =
      Enum.map_join(sections, "\n", fn
        {_, [], _} ->
          ""

        {title, checks, open} ->
          "<details#{open}>\n<summary>#{title} (#{length(checks)})</summary>\n\n" <>
            results_table(checks) <> "\n</details>\n"
      end)

    """
    ## Data-layer conformance results

    Matching a recorded gap does not mean the feature is supported. Excluded or skipped checks did not run. Actual values below come from this run. Saved reports can be compared by stable scenario ID.

    | Adapter | Declared status | Execution | Count |
    | --- | --- | --- | ---: |
    #{count_rows}

    #{comparison}
    #{details}
    """
  end

  defp results_table(rows) do
    body =
      rows
      |> Enum.sort_by(&{&1.scenario, &1.adapter})
      |> Enum.map_join("\n", fn row ->
        "| #{code("#{row.adapter} #{row.scenario}")} | #{verdict(row)} | " <>
          "#{code(row.expected)} | #{code(row.actual)} | #{code(row.accepted)} |"
      end)

    "| Check | Result | Intended | Observed | Accepted by this test |\n" <>
      "| --- | --- | --- | --- | --- |\n" <> body <> "\n"
  end

  def verdict(%{execution: :matched, status: :supported}), do: "PASS"
  def verdict(%{execution: :matched, status: :unresolved}), do: "OBSERVATION MATCHED"
  def verdict(%{execution: :matched}), do: "GAP MATCHED"
  def verdict(%{execution: execution}), do: execution |> to_string() |> String.upcase()

  def compact(text, limit \\ 800) do
    text =
      text
      |> String.replace(~r/\e\[[0-9;]*m/, "")
      |> String.replace("\r", "\\r")
      |> String.replace("\n", "\\n")
      |> String.replace("\t", "\\t")

    if String.length(text) > limit, do: String.slice(text, 0, limit) <> " [truncated]", else: text
  end

  def code(text) do
    escaped =
      text
      |> compact(1500)
      |> String.replace("&", "&amp;")
      |> String.replace("<", "&lt;")
      |> String.replace(">", "&gt;")
      |> String.replace("|", "&#124;")
      |> String.replace("`", "&#96;")

    "<code>#{escaped}</code>"
  end

  @doc "Results for the pinned set go in `results/`; other sets in `results/<set>/`."
  def dependency_set, do: System.get_env("CONFORMANCE_DEPS", "pinned")

  def results_dir do
    case dependency_set() do
      "pinned" -> "results"
      set -> Path.join("results", set)
    end
  end

  def write_results!(rows) do
    dir = results_dir()
    File.mkdir_p!(dir)
    name = Adapter.selected() |> Enum.map_join("-", & &1.id())
    rows = Enum.sort_by(rows, &{&1.scenario, &1.adapter})
    counts = Enum.frequencies_by(rows, &"#{&1.status}/#{&1.execution}")

    report = %{
      schema_version: 2,
      environment: environment(),
      counts: counts,
      scenarios: rows,
      meaning: "A matched gap expectation is not feature conformance."
    }

    markdown = summary(rows, "")
    File.write!(Path.join(dir, "#{name}.json"), Jason.encode!(report, pretty: true) <> "\n")
    File.write!(Path.join(dir, "#{name}.md"), markdown)

    File.write!(
      Path.join(dir, "features-#{name}.md"),
      Ash.Conformance.Report.FeatureReport.markdown(rows, Adapter.selected(), :observed)
    )

    if path = summary_path(), do: File.write!(path, markdown, [:append])

    IO.puts("\n" <> console(rows))
    IO.puts("\nData-layer contracts: #{inspect(counts)}\nReport: results/#{name}.md")
  end

  @doc """
  Runtime, dependency and database versions for each selected adapter.

  Capabilities and results can depend on these, as they can on repo settings
  such as AshSQLite's write transactions.
  """
  def environment do
    Map.new(Adapter.selected(), fn adapter ->
      :ok = adapter.checkout!()

      try do
        {adapter.id(),
         adapter
         |> Ash.Conformance.Benchmark.environment()
         |> Map.put(:local_dependency_overrides, local_overrides())
         |> Map.put(:dependency_set, dependency_set())}
      rescue
        exception ->
          {adapter.id(),
           %{
             limitation: "Environment unavailable: #{Exception.message(exception)}",
             local_dependency_overrides: local_overrides()
           }}
      after
        adapter.checkin!()
      end
    end)
  end

  @doc "Adapter dependencies replaced by local checkouts for this run."
  def local_overrides do
    for variable <-
          ~w(CONFORMANCE_ASH_SQL_PATH CONFORMANCE_ASH_SQLITE_PATH CONFORMANCE_ASH_POSTGRES_PATH),
        path = System.get_env(variable),
        path not in [nil, ""],
        into: %{},
        do: {variable, path}
  end

  def summary_path do
    case System.get_env("GITHUB_STEP_SUMMARY") do
      path when path in [nil, ""] -> nil
      path -> path
    end
  end
end
